name = "astronumeris-notifications"
main = "workers/cron-notifications.ts"
compatibility_date = "2023-12-01"

# Run every hour to check for user timezones
[triggers]
crons = ["0 * * * *"]

# KV Namespace binding 
[[kv_namespaces]]
binding = "PUSH_SUBSCRIPTIONS"
id = "078b9083c5024d2d80ec2245dbb318b8"
